---
title: "Conclusion"
author: "Lee Kennedy-Shaffer, PhD"
date: "June 10, 2025"
format: 
  revealjs:
    embed-resources: true
    self-contained: true
editor: visual
---

## Additional Methods

There are new methods for quasi-experiments coming out frequently! The staggered adoption setting, non-binary treatments, and inferential approaches are especially hot research areas.

. . .

Other quasi-experimental methods include:

-   Interrupted time series
-   Instrumental variables
-   Regression discontinuity

## How to Approach an Analysis

::: incremental
1.  Plot treatment status over time
2.  Carefully consider similarity of units (levels, trends, known & unknown covariates)
3.  Carefully consider heterogeneities of effect that are possible
4.  Determine desired estimand
5.  Conduct simplest analyses (TWFE, dynamic TWFE) and plot pre- and post-trends
6.  Conduct more complex analyses as needed
:::

## Uses and Advantages in Epidemiology

::: {.fragment .fade-in-then-semi-out}
-   Can use routine data
:::

::: {.fragment .fade-in-then-semi-out}
-   Fewer covariates required
:::

::: {.fragment .fade-in-then-semi-out}
-   Evaluate population-level impacts
:::

::: {.fragment .fade-in-then-semi-out}
-   Clear interpretations/different set of assumptions
:::

## Challenges/Limitations in Epidemiology

::: {.fragment .fade-in-then-semi-out}
-   ATT is not usually target
:::

::: {.fragment .fade-in-then-semi-out}
-   Limited generalizability
:::

::: {.fragment .fade-in-then-semi-out}
-   Still require untested assumptions
:::

::: {.fragment .fade-in-then-semi-out}
-   Limited inferential methods
:::

::: {.fragment .fade-in-then-semi-out}
-   Limited research on integrating with other study designs
:::

## Research Needed

::: incremental
-   Which epi settings are conducive to these methods? Which are not?

-   How do we translate the statistical/causal assumptions into meaningful subject-matter questions?

-   Which of these advanced methods are most useful in epi? How should they be selected in principled ways?
:::

## Additional Info

All materials: <https://github.com/leekshaffer/Epi-QEs/>

References list in main folder

Contact me: [lee.kennedy-shaffer\@yale.edu](mailto:lee.kennedy-shaffer@yale.edu)
